//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassGenVer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassGenVer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimitar12@
        ///Father12#
        ///1Reckless@
        ///2Gimme&amp;
        ///3Dollars$$$
        ///1Dollar$
        ///5Precent%
        ///8Stars***
        ///1Slash?
        ///1What?
        ///2What?
        ///4WhoIsThat?
        ///6TheDevil^^^
        ///1Peace*
        ///0THugs**
        ///4Backgammon@.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to school12
        ///break12
        ///bright1
        ///1bear
        ///2forest
        ///9toshiba
        ///78column
        ///prestige2
        ///2pacisalive
        ///triangle3
        ///rectangle4
        ///hextangle6
        ///funny951
        ///smile7
        ///lucky777
        ///stupid000
        ///mistake13
        ///nostalgic5
        ///7lucky7
        ///3sister
        ///2brother
        ///1mother
        ///1father.
        /// </summary>
        internal static string numbers {
            get {
                return ResourceManager.GetString("numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimitar12@
        ///father12#
        ///1reckless@
        ///2gimme&amp;
        ///3dollars$$$
        ///1dollar$
        ///5precent%
        ///8stars***
        ///1slash?
        ///1what?
        ///2what?.
        /// </summary>
        internal static string numbersSymbols {
            get {
                return ResourceManager.GetString("numbersSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daughter12
        ///Mother666
        ///Lucky777
        ///Monkey111
        ///Ugly0
        ///Brother124
        ///Villan555
        ///GumBall123
        ///DrumBall444
        ///GitHub888
        ///
        ///.
        /// </summary>
        internal static string numbersUpper {
            get {
                return ResourceManager.GetString("numbersUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to school@
        ///brother!
        ///sister?
        ///mistake*
        ///billiards&amp;
        ///bingo***
        ///father@#
        ///mother#
        ///honey^
        ///biggiesmalls***.
        /// </summary>
        internal static string symbols {
            get {
                return ResourceManager.GetString("symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father
        ///Mother
        ///Daughter
        ///Billiards
        ///Gingerbread
        ///FrankSinatra
        ///Monkey
        ///Donkey
        ///ShyBird.
        /// </summary>
        internal static string upper {
            get {
                return ResourceManager.GetString("upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donkey!
        ///Monkey@
        ///Lucky&amp;
        ///Billiards***
        ///Ugly@#$
        ///Dollars$$$
        ///Dollar$
        ///Funky_
        ///FunkyMonkey@
        ///Billy@!.
        /// </summary>
        internal static string upperSymbols {
            get {
                return ResourceManager.GetString("upperSymbols", resourceCulture);
            }
        }
    }
}
